{
 "title": "站点统计",
 "tags": [ "site summary" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "${VAR_BASE}" },
   { "name": "path", "query": "$base.*" },
   { "name": "group", "label": "domain", "query": "$base.$path.summary.*" },
   { "name": "browser", "query": "$base.$path.summary.$group.*" },
   {
    "name": "connectivity",
    "query": "$base.$path.summary.$group.$browser.*"
   },
   { "name": "function", "query": "min, mean,median,p90,max" }
  ]
 },
 "panels": [
  { "title": "可视化指标", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "加载性能",
   "type": "graph",
   "description": "加载性能指标",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms", "label": "耗时" }
   ],
   "targets": [
    {
     "target": "alias(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.firstPaint.$function, '首次绘制')"
    },
    {
     "target": "alias(sitespeed_io.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.$function, '速度指数')"
    }
   ]
  },
  {
   "title": "技术指标",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "前后端耗时对比",
   "type": "graph",
   "description": "The max time spent in frontend vs backend time. \n\nThe backend time is the time it takes for the network and the server to generate and start sending the HTML. It is collected using the Navigation Timing API taking the responseStart minus navigationStart.\n\nThe frontend time is the time it takes for the browser to parse and create the page.  It is collected using the Navigation Timing API by taking the loadEventStart minus responseEnd.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "占比" }
   ],
   "targets": [
    {
     "target": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.$function, #C), '后端')",
     "targetFull": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.$function, sumSeries($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.median,$base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.median)), '后端')"
    },
    {
     "target": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.$function, #C), '前端')",
     "targetFull": "alias(asPercent($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.$function, sumSeries($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.backEndTime.median,$base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.frontEndTime.median)), '前端')"
    }
   ]
  },
  {
   "title": "导航耗时",
   "type": "graph",
   "description": "[Navigation Timing API](https://www.w3.org/TR/navigation-timing/) metrics.",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "耗时" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.redirectionTime.$function, 'Redirect')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.domainLookupTime.$function, 'DNS')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.serverConnectionTime.$function, 'TCP')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.serverResponseTime.$function, 'TTFB')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.firstPaint.$function, 'First Paint')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.visualMetrics.SpeedIndex.$function, 'Speed Index')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.browsertime.pageTimings.pageLoadTime.$function, 'Full Loaded')"
    }
   ]
  },
  {
   "title": "请求数",
   "type": "graph",
   "description": "不同类型资源的网络请求数量",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "个数" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.html.requests.$function, 'HTML')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.javascript.requests.$function, 'JS')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.css.requests.$function, 'CSS')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.favicon.requests.$function, 'Favicon')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.image.requests.$function, 'Image')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.font.requests.$function, 'Font')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.json.requests.$function, 'JSON')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.plain.requests.$function, 'Plain')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.other.requests.$function, 'Other')"
    }
   ]
  },
  {
   "title": "传输大小",
   "type": "graph",
   "description": "不同类型资源的网络传输占用带宽大小",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes", "label": "大小" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.html.transferSize.$function, 'HTML')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize.$function, 'JS')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.css.transferSize.$function, 'CSS')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.favicon.transferSize.$function, 'Favicon')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.image.transferSize.$function, 'Image')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.font.transferSize.$function, 'Font')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.json.transferSize.$function, 'JSON')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.plain.transferSize.$function, 'Plain')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.pagexray.contentTypes.other.transferSize.$function, 'Other')"
    }
   ]
  },
  {
   "title": "代码审查",
   "type": "graph",
   "description": "代码审查评分",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.coach.score.$function, '综合')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.coach.performance.score.$function, '性能')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.coach.bestpractice.score.$function, '最佳实践')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.coach.accessibility.score.$function, '可访问性')"
    },
    {
     "target": "alias($base.$path.summary.$group.$browser.$connectivity.coach.privacy.score.$function, '隐私')"
    }
   ]
  }
 ]
}